# send all logs of the docker containers
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            #  dont send filebeat container logs
            not:
              contains:
                docker.container.image: filebeat
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
logging.metrics.enabled: false
output.logstash:
  hosts: ["logstash-host.example.com:5044"]
